name: Markdown Prose Linter
description: Run proselint on Markdown files in the repository
author: Quanhao Li
shell: bash  # Replace with the shell you want to use, e.g., bash, pwsh, sh, etc.

on:
  push:
    branches:
      - main  # Adjust based on your repository's default branch

runs:
  using: "composite"
  steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y proselint

      - name: Run proselint on Markdown files
        run: |
          find . -name "*.md" -type f -exec proselint {} +
